# Generated by Django 2.2.7 on 2019-11-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20191114_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subway',
            name='bread',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subway',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subway',
            name='sandwitch',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subway',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subway',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
