# Generated by Django 2.2.7 on 2019-11-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subway',
        ),
    ]
