# Generated by Django 2.2.7 on 2019-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subway', '0002_delete_subway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('menu', models.CharField(max_length=20)),
                ('bread', models.CharField(max_length=10)),
                ('vegetalbe', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('drink', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
